[project]
name = "ipynb2pdf"
version = "2026.09.09"
description = "Convert a Jupyter notebook to a PDF with nice syntax highlighting and formatting."
readme = "README.md"

# Google Colab version of Python
requires-python = "==3.13.15"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "nbconvert>=7.17.1",
    "networkx>=3.6.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-image>=0.26.0",
    "scipy>=1.18.1",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 79

[tool.ruff.format]
preview = true
